#!/usr/bin/env python3
import socket, os, sys, re
from logger import Logger
from socket_ctx import open_socket
from sefinalum import Sefinalum, frame

log = Logger(4)

def run(dst_host, dst_port):
    with open_socket(dst_host, dst_port) as sock:

        data = frame.open('sh')
        while len(data):
            sent = sock.send(data)
            data = data[sent:]

        while (data := os.read(0, 1024)) != b'':
            send(data, sock)

        data = frame.close()
        while len(data):
            sent = sock.send(data)
            data = data[sent:]
            
        data = frame.end()
        while len(data):
            sent = sock.send(data)
            data = data[sent:]

def send(msg, sock):
    data = frame.write(msg)
        
    while len(data):
        sent = sock.send(data)
        log.info('SEND', f'BYTES: <{sent}>')
        data = data[sent:]

if __name__ == '__main__':

    dst_serv = sys.argv[1]
    dst_tokens = dst_serv.split(':')
    dst_host = dst_tokens[0]
    dst_port = int(dst_tokens[1])
    
    run(dst_host, dst_port)
