#!/usr/bin/env python3
import socket, os, sys, re    
from sefinalum import Sefinalum
from logger import Logger

log = Logger(4)

def run():
    try:
        source_addr = ''
        source_port = int(sys.argv[1])
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.bind((source_addr, source_port))
        sock.listen(1)
        
        conn, addr = sock.accept()
        log.info('SOCK ACCEPT', f'ADDR: <{addr}>')
        
    
        fsm = Sefinalum(3)
    
        data = conn.recv(256)
        fsm.update({'data': data, 'end': 'end'})
        while True:
    
            status = fsm.call()
            data = fsm['data']

            if status == 'end':
                log.info('SEQ END', 'Sequence termination directive received')
                break
                
            elif status:
                incoming = conn.recv(4)
                data += incoming
                log.info('SOCK RECEIVE', f'RECV/DATA SIZE: <{len(incoming)}>/<{len(data)}>')
                fsm.update({'data': data})          
        
    except KeyboardInterrupt:
        pass
            
    conn.close()

if __name__ == '__main__':
    run()
